### ISSUE TITLE
Program might be broken.

### ISSUE THREAD

**Issue by supertrio17** [TcNobo/TcNo-Acc-Switcher#109]
Hi, so in new update (4.2) nothing works for me. Program doesn't start on startup, when closing and trying to run it again it says that instance is already running but there is no instance in task manager (edit, instance is called dotnet.exe now, after closing it starts again but same thing happens when closing). Holding alt to kill all processes doesn't work (probably due to .exe file being called dotnet.exe). Clicking close to tray pops up an error message with "Could not start tray application!", however changing profiles still works. Any help?

Edit: When trying to reinstall under currently installed runtimes it says "Version conversion failed!"

Edit2: After installing CEF it gives out an error:
![image](https://user-images.githubusercontent.com/57882120/144931507-4478ed7a-72cb-41c9-a8aa-8fb34b9d57a4.png)

**Comment by supertrio17** [comment]
I took a look inside 2 startup folders, and found Tray shortcut, after starting Tray application it gave out an message:
![image](https://user-images.githubusercontent.com/57882120/144932508-c97a6ade-3b4c-440d-a6c1-c202c65a303c.png)
So I'm guessing this has to do with compiling the program or internal mistake while updating. Hope I helped

**Comment by supertrio17** [comment]
After changing the name of the folder from "C:\Program Files\TcNo-Acc-Swithcer" to "C:\Program Files\dotnet" everything seems to work like expected. Hope I helped

**Comment by TcNobo** [comment]
This should be fixed. (All of the issues you mentioned here).
Try running the updater again and let me know if things work as usual - Unless you've already updated...
In which case, update again and let me know if things are better.

**Comment by supertrio17** [comment]
Now it shows me this
![image](https://user-images.githubusercontent.com/57882120/145225520-4cfa060d-4303-4f42-9151-7a56affe10b5.png)
First it said I needed desktop version (which I already had), so I uninstalled it and installed it again, and now it says I just need missing frameworks, so I installed every single one from that site, but still no luck. Tried reinstalling TcNo and restarting but same thing again.

**Comment by TcNobo** [comment]
Yes, since the update you need .NET 6 installed, not .NET5. New in the last update.
After updating you should be able to launch the program.

See: https://github.com/TcNobo/TcNo-Acc-Switcher/wiki#your-first-launch

**Manual runtime install:**
-   **WebView2 Runtime:**  [Install](https://go.microsoft.com/fwlink/p/?LinkId=2124703).
-   **Microsoft .NET 6 Desktop Runtime:** [Download x64, under Run Desktop Apps](https://dotnet.microsoft.com/download/dotnet/6.0/runtime).
-   **ASP.NET Core 6 Runtime:** [Download Hosting Bundle, under Run Server Apps](https://dotnet.microsoft.com/download/dotnet/6.0/runtime).

**Comment by supertrio17** [comment]
> Yes, since the update you need .NET 6 installed, not .NET5. New in the last update. After updating you should be able to launch the program.
> 
> See: https://github.com/TcNobo/TcNo-Acc-Switcher/wiki#your-first-launch
> 
> **Manual runtime install:**
> 
> * **WebView2 Runtime:**  [Install](https://go.microsoft.com/fwlink/p/?LinkId=2124703).
> * **Microsoft .NET 6 Desktop Runtime:** [Download x64, under Run Desktop Apps](https://dotnet.microsoft.com/download/dotnet/6.0/runtime).
> * **ASP.NET Core 6 Runtime:** [Download Hosting Bundle, under Run Server Apps](https://dotnet.microsoft.com/download/dotnet/6.0/runtime).

Yes I did, I installed .NET 6 not 5. When CMD pop's up it says that everything is installed but than I get this error. I'll try reinstalling other runtimes.

**Comment by TcNobo** [comment]
Odd... And you downloaded a fresh copy from GitHub today? There was 1 version on the 6th that was a little broken ~
https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2021-12-07_00

**Comment by supertrio17** [comment]
Yeah, you are right, I downloaded that broken version. I'll try to install new one as soon as I get home. I'll keep you updated

**Comment by supertrio17** [comment]
It seems like that's the only version that you pushed today. I only see 2021-12-07-00

**Comment by supertrio17** [comment]
I actually did download latest 07 version. I'm going to try uninstalling all runtimes and let the program do it.

**Comment by supertrio17** [comment]
After uninstalling every single runtime, and letting program install runtimes itself, everything works as expected. I think older versions were making this problem, but I'm not completely sure.
