### ISSUE TITLE
could not close Service:steamservice.exe, GameOverlayUI.exe

### ISSUE THREAD

**Issue by EDZX75** [TcNobo/TcNo-Acc-Switcher#152]
that the problem after fix u gave. i think that the main problem do u know how to solve?

**Comment by TcNobo** [comment]
Try running the account switcher as admin?
Or see if changing `TcNo Account Switcher > Steam > Settings > Closing Method` to the other options, then restarting helps.
![TcNo-Acc-Switcher_main_LgsRW6F7AJ](https://user-images.githubusercontent.com/10319195/152653458-37d031e6-1092-45b9-a13c-e979d0d0580e.png)


Is Steam running as Admin, or anything like that?

**Comment by EDZX75** [comment]
its says down on thcno app but nothing happen with the steam

**Comment by EDZX75** [comment]
![image](https://user-images.githubusercontent.com/98840074/152654246-1b9a5298-f7e9-4179-b6ee-68586a1e67e0.png)
**** this when i use taskkill
![image](https://user-images.githubusercontent.com/98840074/152654275-2319ff0d-8779-4fc9-b6ca-dfa13d7a81a0.png)
and this when im use the combine but nothing happen

**Comment by EDZX75** [comment]
![image](https://user-images.githubusercontent.com/98840074/152678338-906ad5c9-d414-4043-a6d4-aa003cde0c5a.png)
i found new issue when im restarting my pc maybe this can sove my problem

**Comment by TcNobo** [comment]
The error message comes from the Tray application trying to start, without having an account saved and swapped to at least once. The file: `%AppData%\TcNo Account Switcher\Tray_Users.json` is missing on your computer - Created after changing accounts.

As for it not closing Steam properly, I'll have a release out in a few minutes that should fix it.

**Comment by TcNobo** [comment]
Try downloading the pre-release here, and let me know if things are fixed :)
https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-02-07_00

**Comment by EDZX75** [comment]
it still the same idk why 
![image](https://user-images.githubusercontent.com/98840074/152807293-a1877bc9-291d-472a-a762-00ed1ffc5dd2.png)

**Comment by TcNobo** [comment]
- Did running the account switcher as admin help?
- Did changing the closing method back to TaskKill, restarting the account switcher and trying again work?
  
![image](https://user-images.githubusercontent.com/10319195/152830776-2e60b311-55f5-4173-843a-863b27f81cd7.png)

**Comment by EDZX75** [comment]
Idk the .json files not created when im swiching account manualy and the problem still failed to close steam
![image](https://user-images.githubusercontent.com/98840074/152890522-cc41bdba-ef1e-478d-87c8-b3f3a588b277.png)
![image](https://user-images.githubusercontent.com/98840074/152890605-21a3dce3-6a6b-48b4-918a-0f82edb166d8.png)

**Comment by EDZX75** [comment]
Ok thx dude i have fixed my problem but i because the steam service exe and gameui not closing i close it manualy using task manager and it works thanks a lot ur aplication really helps me and i appreciate for helping my problem :D

**Comment by TcNobo** [comment]
Closing it manually will help fix the problem temporarily... But I will keep on the lookout for a more reliable method. There are much fewer reports of issues like this nowadays, but I assume some people are still running into problems.

**Comment by EDZX75** [comment]
keep ur good work mate thx for fixing mine :D
