### ISSUE TITLE
Epic Games Launcher 19.0.1 no longer switches accounts after latest update

### ISSUE THREAD

**Issue by itskreisler** [TcNobo/TcNo-Acc-Switcher#482]
**Describe the bug**
When trying to switch accounts using the program, the Epic Games Launcher restarts but stays logged into the same account. The account does not actually switch to the one selected in the program. This issue started occurring after updating to version 19 — it worked correctly in version 18

**To Reproduce**
1. Open the account switcher program
2. Select a different Epic Games account.
3. Wait for the launcher to restart.
4. Notice that it reopens with the same account instead of switching.

**Expected behavior**
The launcher should restart and automatically log into the selected account, switching correctly as it did in version 18.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19045 Compilación 19045
 - Epic Games Launcher: 19.0.1

**Additional context**
This issue only started after updating to version 19. Downgrading to version 18 restores normal account switching behavior.

**Comment by Sel-en-ium** [comment]
Manually swapping the `GameUserSettings,ini` file also just stopped working for me today or yesterday.

`%USERPROFILE%\AppData\Local\EpicGamesLauncher\Saved\Config\WindowsEditor\GameUserSettings.ini`

**Comment by ThisisZeth** [comment]
same here, doesn't work with Epic anymore

**Comment by jawful** [comment]
Same problem. Thank you for posting this because I spent the last 30 minutes deleting caches, reinstalling software and generally pulling my hair out! So I'm more than happy to see it's not my fault!

**Comment by campsdc77** [comment]
Same here just noticed today deleted everything and reinstalled no change. Stays on same account no matter which one I pick.

**Comment by Napali89** [comment]
For anyone wanting a quick fix for it.
in the **platforms.json** change this line:
` "%LocalAppData%\\EpicGamesLauncher\\Saved\\Config\\Windows\\GameUserSettings.ini": "GameUserSettings.ini",`
to
` "%LocalAppData%\\EpicGamesLauncher\\Saved\\Config\\WindowsEditor\\GameUserSettings.ini": "GameUserSettings.ini",`

it'll work again afterwards

**Comment by fedorenko18041988-sys** [comment]
If it's not too much trouble, please attach the replacement files.

**Comment by fedorenko18041988-sys** [comment]
[Platforms.json](https://github.com/user-attachments/files/23431819/Platforms.json)
[Platforms.json.bak.json](https://github.com/user-attachments/files/23431820/Platforms.json.bak.json)

**Comment by bananman1982** [comment]
> > For anyone wanting a quick fix for it. in the **platforms.json** change this line: ` "%LocalAppData%\\EpicGamesLauncher\\Saved\\Config\\Windows\\GameUserSettings.ini": "GameUserSettings.ini",` to ` "%LocalAppData%\\EpicGamesLauncher\\Saved\\Config\\WindowsEditor\\GameUserSettings.ini": "GameUserSettings.ini",`
> > it'll work again afterwards
> 
> it worked thanks and you have to make the change in **_platforms.json_** and **_platforms.jsonbak_** so it work

How do you do this please

**Comment by donnyad** [comment]
i went ahead and pushed this commit, hopefully dev fixes it officially soon. thank **Napali89**

**Comment by TCNOco** [comment]
Thanks to everyone for coming together over this! I will add the changes and push a new version. Really appreciate it  :)

**Comment by TCNOco** [comment]
Thanks again for the help all! I have pushed a new update: https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2025-11-09_00

This also bumps .NET to 9 and a few other packages used in building it all. Things should hopefully be even more stable.

Please let me know if you have any issues! I will leave this issue open for a few days, but consider it solved.

**Comment by jawful** [comment]
Update works great!

**Comment by donnyad** [comment]
@SlimeDread, im still using the manual method, i just set the config file to read only after making changes. haven’t swapped to the new update but i have noticed occasionally ill have to resign into a profile this is most likely a epic games auth thing though might just be user error. Manually resave your profiles after seeing your config to read only

**Comment by H3lixxx** [comment]
It's still broken for me. Only one account is being remembered. I have 5 epic accounts and I use two of those daily. Swapping back & forth. Tcno account switcher broke for me on the 8th of nov. Then I noticed the update msg so updated tcno. Same thing. Swapping accounts puts me back in to the same epic account. Add new doesnt add a new acct. I've peeked at the logs and it looks like a directory path doesnt exist but I get no popup telling me this. I've tried to figure this out on my own but not sure what the problem is. I've used (and loved) this app for exactly a year. Flawless. Till now 😭 

Does downgrading Tcno account switcher help people still? I'm sad I have to manually swap accounts thru the epic launcher now. (first world problem I know, but I loved this app!)

**Comment by BeFaRd** [comment]
> It's still broken for me. Only one account is being remembered. I have 5 epic accounts and I use two of those daily. Swapping back & forth. Tcno account switcher broke for me on the 8th of nov. Then I noticed the update msg so updated tcno. (which also installed .net framework 9) Same thing. Swapping accounts puts me back in to the same epic account. Add new doesnt add a new acct. I've peeked at the logs and it looks like a directory path doesnt exist but I get no popup telling me this. I've tried to figure this out on my own but not sure what the problem is. I've used (and loved) this app for exactly a year. Flawless. Till now 😭
> 
> Does downgrading Tcno account switcher help people still? I'm sad I have to manually swap accounts thru the epic launcher now. (first world problem I know, but I loved this app!)

The solution is above 

__________________________________________________

> For anyone wanting a quick fix for it. in the **platforms.json** and **platforms.jsonbak** change this line: ` 


"%LocalAppData%\\EpicGamesLauncher\\Saved\\Config\\Windows\\GameUserSettings.ini": "GameUserSettings.ini",` to ` "%LocalAppData%\\EpicGamesLauncher\\Saved\\Config\\WindowsEditor\\GameUserSettings.ini": "GameUserSettings.ini",`
> 
> it'll work again afterwards

**Comment by H3lixxx** [comment]
> The solution is above

Thanks but for me that path doesnt exist. Neither does the file platforms.jsonbak so that fix didnt work for me.
Since I'd already updated tcno account switcher, the path had already been corrected in the platforms.json file but if I copy & paste that path in to explorer I get an error: (the same one shown in the log but doesnt pop up on screen. On screen I see the "success msg" even tho I've just been logged back in to the exact same account)

<img width="695" height="149" alt="Image" src="https://github.com/user-attachments/assets/44bcfaeb-8763-412b-ae20-943a2d247146" />

I'm a gamer. I dont understand what the issue is in my case. My epic games (the actual game downloads) are on a different drive, however I didnt change the install path for the epic games launcher. My apologies if I'm irritating you.

**Comment by itskreisler** [comment]
I understand, so it was a github thing at the time of pasting the code, haha, but tell me you have already been able to solve it, I made the changes in platforms.json and platforms.jsonbak, I edited those 2 files and it worked for me, if you still haven't been able to solve it let me know, we can all help you 

> > You have a syntax error - you're using a double slash (`\\`) instead of a single backslash (`\`). In any case, you're mistyping the path
> 
> Hrm well if this is the case, there are many paths in the same file have double backslashes. 6 lines above the one in my screenshot is this line:  (I'll take another screenshot coz when I press update comment, for some reason the \\'s from what I pasted here are posted as single \'s  0.o)
> 
> and many more below that. I havent edited this file at all, just looked in it and compared to what was suggested here for the fix.
> (edited coz I pasted the wrong line. oops)
> 
> <img width="1417" height="733" alt="Image" src="https://github.com/user-attachments/assets/af1813c9-57ea-46ec-a5c0-6b643d3d2f8b" />

**Comment by donnyad** [comment]
Close program in task manager.
Edit the json.
Right click json.
Properties.
Set json to read only.
Open program.
You may have to delete and resign into accounts again one more time.

**Comment by H3lixxx** [comment]
> Close program in task manager.

Its not running therefore not in taskman. But I'll try your fix later too, if TCNO's copy/paste doesnt work

**Comment by H3lixxx** [comment]
> I'm not sure about the jsonbak I don't recall making anything that would make that file. Could be an editor that placed that there, or something I've forgotten about.

Someone else in this thread mentioned to copy & paste that specific line in to both the json & jsonbak files (I dont have the bak file)


> [@H3lixxx](https://github.com/H3lixxx) Can you please post your existing broken `Platforms.json` file from `%AppData%\TcNo Account Switcher\Platforms.json`? Just drag and drop it onto the issue.

It appears there's an account id in this section: Albion Online Client:LastUsedAccountId  is there a way to dm my file to you rather than post publically here? Since you'd like to see the Platforms.json file that I got with the update on the 9th nov, I wont try to copy & paste the file you replacement file you personally pasted here earlier today. In case others have the same issue as me its prolly better you see the current file that isnt working for me. Right?

Thank you for your time btw. Im going nuts here

**Comment by SlimDread** [comment]
> Close program in task manager. Edit the json. Right click json. Properties. Set json to read only. Open program. You may have to delete and resign into accounts again one more time.

nope doesn't work

**Comment by H3lixxx** [comment]
> The ID that appears in the `Platforms.json` template file is a unique location in the registry for AO. I assume it's the game's ID, or something similar, and is the same for everyone.

👍 




> But yes, you can get the file to me through Discord. I am `troublechute`.
> Here is an invite to my Discord server: https://discord.gg/MQS4SJpwPt

Thx, joined and dm'd you. BTW the link in your help video to discord doesnt work. Link isnt "expired" just doesnt take you to any server. I clicked that link before making an acct here on github just to post in this thread 😊
