### ISSUE TITLE
Failed to load steamui.dll

### ISSUE THREAD

**Issue by HarveyB02** [TcNobo/TcNo-Acc-Switcher#58]
Launching steam through the application causes the error "Failed to load steamui.dll". Steam still opens fine when opened normally.
This occurs when pressing any button in the application that will open steam

**Comment by TcNobo** [comment]
Check that you have the correct Steam install selected in options.
Make sure that the program opens Steam as admin if you normally open Steam as admin.

This is an odd error, as it doesn't do anything to Steam itself, other than swapping out files and starting it again. This isn't an error that should be caused by this program.

**Comment by Xxforlife** [comment]
> 
> 
> I ran into this same error after an OS reinstall. Note my Steam install uses a non-default path on a secondary HDD so all of my config files remained after the OS wipe, plus I migrated by hand all of my old appdata from "C:\Users\xxx\Appdata\Local\Steam" into my fresh OS, so the Account Switcher saw both of my Steam accounts right away even before logging properly into both of them. Weirdly enough, both of my Steam accounts launched fine when logging in though the Steam client, but the Account switcher returned this "Failed to load steamui.dll" error no matter what. I solved it by going into "Settings wheel>Other Tools>Advanced Cleaning>Clean my login history" and chose to delete loginusers.vdf. After that I re-added my accounts from within the Account Switcher and everything worked fine this time.


I ran into this error also today while using a secondary hard drive.

**Comment by TcNobo** [comment]
I was able to get this while adding a new account on a fresh install of Windows, so I may be able to figure out why :)

**Comment by Albanight** [comment]
This is happening as well for me. It could be because I have steam installed at "C:\Steam" not "C:\Program Files (x86)\Steam"

**Comment by Riyyi** [comment]
I just had this issue. Logged into 2 different accounts on Steam using the `Change Account...` option, then installed TcNo, both accounts showed up right away but would throw the error. Fixed it by deleting `loginusers.vdf` and `loginusers.vdf_last`, then logging into 1 account via normally started Steam so `loginusers.vdf` would get recreated. Then starting TcNo again and adding both accounts, starting with the account I logged in with first (don't know if that matters).

**Comment by TcNobo** [comment]
~~ Is everyone here on Windows 10? I have only done extensive testing on Windows 10 x64. I don't want to update to 11 tbh

**Comment by Dieg0Poker** [comment]
Yes, I had this issue on Windows 10.

**Comment by Albanight** [comment]
I was having this on Windows 10. After a simple restart of the program It was fixed.

**Comment by Riyyi** [comment]
Yes, I tested it on Windows 10 Enterprise LTSC x64.

**Comment by TcNobo** [comment]
This is an ancient issue, though I think I've finally found the cause.
Essentially: Steam can't find it's own program files (SteamUI.dll, etc.), as the working directory was not set when launching the program, leading the exe to believe it was alone in a folder somewhere.

This update should fix it for the next release, as well as have a ton of new features!

**Comment by TcNobo** [comment]
Assuming fixed.

**Comment by rush2sk8** [comment]
I'm still running into this problem Win11

**Comment by RyanHiller** [comment]
I'm currently getting this issue on Win10.

**Comment by wabkia** [comment]
just re-installed windows and transfered my tcno folder from %appdata% of the old user. running into this. steam is installed in the default location, didnt change between installs. steam folder in tcno was already set to the correct location, re-selected anyway, didnt fix. i do not think this is fixed, @TcNobo. its unfortunate to have to re-log into multiple accounts. i am using the may26 release in /releases. would be happy to provide u with any info u need.

**Comment by stucka** [comment]
I ran into this problem on Win11, and TcNo's cleaner did not seem to want to delete the loginusers.vcf file through the cleaner as recommended by https://github.com/TcNobo/TcNo-Acc-Switcher/issues/58#issuecomment-906212627 .

However, I found the file in c:\Program Files (x86)\Steam\config and renamed it, started up Steam, logged in again.

Interestingly, each login had a new pair of keys that weren't in the old file; I can only guess this somehow is affecting that error?

		"SkipOfflineModeWarning"		"0"
		"AllowAutoLogin"		"1"

**Comment by jayjakee** [comment]
Restart steam and load it back up as admin and restart tcno too, worked for me.
